server:
  port: 8770
  context-path: /api/
spring:
  application:
    name: cloud-ribbon-server
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://101.37.35.73:3306/mall?useSSL=false
    username: hcon
    password: hconuser
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 1
    maxActive: 20
    maxWait: 5000
    filters: stat,wall
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
  boot:
    admin:
      url: http://localhost:8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
  MaxAutoRetriesNextServer: 0
hystrix:
  default:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 5000
management:
  security:
    enabled: false