server:
  port: 8762
spring:
  application:
    name: cloud-ribbon-server
  zipkin:
    base-url: http://localhost:9411
    enabled: true
eureka:
  client:
    service-url:
      defaultZoone: http://localhost:8761/eureka/
cloud-service-order:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule