server:
  port: 8770
  context-path: /api/
spring:
  application:
    name: cloud-ribbon-server
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  boot:
    admin:
      url: http://localhost:8080
eureka:
  client:
    service-url:
      defaultZoone: http://localhost:8761/eureka/
cloud-service-order:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
logging:
  level:
    com:
      kunlun:
        api:
          service:
            IndexService: debug