server:
  port: 8762
spring:
  application:
    name: cloud-ribbon-server
  zipkin:
    base-url: http://localhost:9000
    enabled: true
eureka:
  client:
    service-url:
      defaultZoone: http://localhost:8761/eureka/